# Generated by Django 4.2.10 on 2024-02-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_details', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='RoleRequiremnts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
            ],
        ),
    ]
